AGE_BINS = [0, 5, 12, 17, 24, 34, 44, 54, 64, 74, 999]
AGE_LABELS = [
    "0-5",
    "6-12",
    "13-17",
    "18-24",
    "25-34",
    "35-44",
    "45-54",
    "55-64",
    "65-74",
    "75 o más",
]

AMM_ID = [6, 9, 21, 18, 26, 31, 39, 46, 19, 48, 49]
PERIFERIA_ID = [10, 12, 25, 41, 45]

ID_TO_CITY_NAME = {
    39: "Monterrey",
    26: "Guadalupe",
    46: "San Nicolás de los Garza",
    6: "Apodaca",
    21: "Escobedo",
    19: "San Pedro Garza García",
    49: "Santiago",
    31: "Juárez",
    18: "García",
    48: "Santa Catarina",
    9: "Cadereyta",
    41: "Pesquería",
    10: "El Carmen",
    12: "Ciénega de Flores",
    25: "Zuazua",
    45: "Salinas Victoria",
    1: "Abasolo",
    2: "Agualeguas",
    4: "Allende",
    5: "Anáhuac",
    7: "Aramberri",
    8: "Bustamante",
    11: "Cerralvo",
    13: "China",
    14: "Doctor Arroyo",
    15: "Doctor Coss",
    16: "Doctor González",
    17: "Galeana",
    20: "General Bravo",
    22: "General Terán",
    23: "General Treviño",
    24: "General Zaragoza",
    47: "Hidalgo",
    28: "Higueras",
    29: "Hualahuises",
    30: "Iturbide",
    31: "Juárez",
    32: "Lampazos de Naranjo",
    33: "Linares",
    3: "Los Aldamas",
    27: "Los Herreras",
    42: "Los Ramones",
    34: "Marín",
    35: "Melchor Ocampo",
    36: "Mier y Noriega",
    37: "Mina",
    38: "Montemorelos",
    40: "Parás",
    43: "Rayones",
    44: "Sabinas Hidalgo",
    50: "Vallecillo",
    51: "Villaldama",
    100: "Fuera de Nuevo León",
    111: "Fuera del País",
    8888: "No sabe",
    9999: "No contesta",
}


DESIRED_ORDERS = {
    "sexo": [
        "Hombre",
        "Mujer",
    ],
    "estudios": [
        "Ninguno",
        "Preescolar",
        "Primaria",
        "Secundaria",
        "Preparatoria o bachillerato general",
        "Bachillerato tecnológico",
        "Estudios técnicos o comerciales con primaria terminada",
        "Estudios técnicos o comerciales con secundaria terminada",
        "Estudios técnicos o comerciales con preparatoria terminada",
        "Normal con primaria o secundaria terminada",
        "Normal de licenciatura",
        "Licenciatura",
        "Especialidad",
        "Maestría",
        "Doctorado",
    ],
    "ingreso": [
        "Sin ingreso",
        "No contesta",
        "Menos de 1 SM ($1 - $8,364)",
        "1-2 SM ($8,364 - $16,728)",
        "2-3 SM ($16,728 - $25,092)",
        "3-4 SM ($25,092 - $33,456)",
        "4-5 SM ($33,456 - $41,820)",
        "5-6 SM ($41,820 - $50,184)",
        "6-7 SM ($50,184 - $58,548)",
        "7-8 SM ($58,548 - $66,912)",
        "8-9 SM ($66,912 - $75,276)",
        "9-10 SM ($75,276 - $83,640)",
        "10 o más SM ($83,640 o más)",
    ],
    "edad": [
        "0-5",
        "6-12",
        "13-17",
        "18-24",
        "25-34",
        "35-44",
        "45-54",
        "55-64",
        "65-74",
        "75 o más",
    ],
    "municipio": [
        "Apodaca",
        "Cadereyta",
        "Escobedo",
        "García",
        "Guadalupe",
        "Juárez",
        "Monterrey",
        "San Nicolás de los Garza",
        "San Pedro Garza García",
        "Santa Catarina",
        "Santiago",
        "AMM",
        "Periferia",
        "Resto NL",
        "Nuevo León",
    ],
    "tipo_escuela": ["Pública", "Privada", "Otro tipo"],
    "tipo_trabajo": ["Trabajo remunerado", "Trabajo no remunerado", "Otro"],
}

DISAGGREGATIONS_TO_TITLES = {
    "totales": "Generales",
    "sexo": "Respuesta por sexo",
    "edad": "Respuesta por edad",
    "municipio": "Respuesta por unidad geográfica",
    "municipio_por_hombres": "Respuesta de HOMBRES por unidad geográfica",
    "municipio_por_mujeres": "Respuesta de MUJERES por unidad geográfica",
    "nivel_max_estudios": "Respuesta por nivel máximo de estudios",
    "particion_modal_agregada_por_municipio": "Partición modal agregada por unidad geográfica",
    "promedio_modo_transporte_y_municipio": "Respuesta promedio por modo de transporte y unidad geográfica",
    "ingreso": "Respuesta por nivel de ingreso",
    "ingreso_por_apodaca": "Respuesta de Apodaca por nivel de ingreso",
    "ingreso_por_cadereyta": "Respuesta de Cadereyta por nivel de ingreso",
    "ingreso_por_escobedo": "Respuesta de Escobedo por nivel de ingreso",
    "ingreso_por_garcia": "Respuesta de García por nivel de ingreso",
    "ingreso_por_guadalupe": "Respuesta de Guadalupe por nivel de ingreso",
    "ingreso_por_juarez": "Respuesta de Juárez por nivel de ingreso",
    "ingreso_por_monterrey": "Respuesta de Monterrey por nivel de ingreso",
    "ingreso_por_san_nicolas": "Respuesta de San Nicolás de los Garza por nivel de ingreso",
    "ingreso_por_san_pedro": "Respuesta de San Pedro Garza García por nivel de ingreso",
    "ingreso_por_santa_catarina": "Respuesta de Santa Catarina por nivel de ingreso",
    "ingreso_por_santiago": "Respuesta de Santiago por nivel de ingreso",
    "ingreso_por_region_amm": "Respuesta del AMM por nivel de ingreso",
    "ingreso_por_region_periferia": "Respuesta de la Periferia por nivel de ingreso",
    "ingreso_por_region_resto_nl": "Respuesta del Resto de NL por nivel de ingreso",
    "nivel_actual_estudios": "Respuesta por nivel actual de estudios",
    "nivel_actual_estudios_por_escuela_publica": "Respuesta por nivel actual de estudios, escuela pública",
    "nivel_actual_estudios_por_escuela_privada": "Respuesta por nivel actual de estudios, escuela privada",
    "tipo_escuela": "Respuesta por tipo de escuela",
    "servicio_salud_donde_se_atendio": "Respuesta por servicio de salud donde se atendió",
    "tipo_servicio_salud_donde_se_atendio": "Respuesta por tipo de servicio de salud donde se atendió",
    "afiliacion_servicio_salud": "Respuesta por servicio de salud con el que cuenta",
    "tipo_consulta": "Respuesta por tipo de consulta",
    "trabajo_remunerado": "Respuesta por actividad laboral remunerada",
    "trabajo_remunerado_por_hombres": "Respuesta de HOMBRES por actividad laboral remunerada",
    "trabajo_remunerado_por_mujeres": "Respuesta de MUJERES por actividad laboral remunerada",
    "tipo_trabajo": "Respuesta por tipo de actividad laboral",
    "tipo_trabajo_por_hombres": "Respuesta de HOMBRES por tipo de actividad laboral",
    "tipo_trabajo_por_mujeres": "Respuesta de MUJERES por tipo de actividad laboral",
}

DERIVED_NEXT: list[tuple[str, str]] = [
    ("tiempo_trabajo", "p3_1"),
    ("prestaciones", "p5_1"),
    ("trabajo_formal", "p5_1"),
    ("quehaceres_hogar", "p7_1"),
    ("cuidados_personas", "p8_1"),
    ("total_min_trabajo_rem_y_norem", "p1"),
    ("ocio", "p9_1"),
    ("tiempo_espera_consulta", "p103_1"),
    ("al_menos_un_problema_mental", "p107_1"),
    ("tiempo_espera", "p21_1"),
    ("costo_total_viaje", "p24"),
    ("tiempo_ida", "p27_1"),
    ("tiempo_regreso", "p28_1"),
    ("tiempo_total_traslado", "tiempo_ida"),
    ("usa_transporte_publico", "p17"),
    ("usa_metro", "p17"),
    ("victima_tp", "p39_1"),
    ("tiempo_camina", "p20_1"),
    ("num_discriminaciones", "p89_1"),
    ("al_menos_una_discriminacion", "p89_1"),
    ("num_acciones_pc", "p161_1"),
    ("al_menos_una_accion_pc", "p161_1"),
    ("p56_ultimos_5_anios", "p55"),
    ("p57_ultimos_5_anios", "p55"),
    ("p58_ultimos_5_anios", "p55"),
    ("p56_ultimos_10_anios", "p55"),
    ("p57_ultimos_10_anios", "p55"),
    ("p58_ultimos_10_anios", "p55"),
    ("al_menos_un_problema_agua", "p66"),
]